# Generated by Django 6.0.7 on 2026-07-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "working_start",
                    models.TimeField(
                        help_text="Clinic-local (EAT) start of working hours, e.g. 09:00"
                    ),
                ),
                (
                    "working_end",
                    models.TimeField(
                        help_text="Clinic-local (EAT) end of working hours, e.g. 17:00"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField(blank=True, null=True)),
                ("slot_time", models.DateTimeField(help_text="Stored in UTC")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("booked", "Booked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="bookings.doctor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "booked")),
                        fields=("doctor", "slot_time"),
                        name="unique_doctor_slot_when_booked",
                    )
                ],
            },
        ),
    ]
